package com.adk.blog.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.adk.blog.model.Post;
import com.adk.blog.service.PostService;

@SpringBootApplication
@RestController
public class MainController {
	
	@Autowired
	private PostService postService;
	
	//NOTE: IDs should be autogenerated and if a user is missing publishdate, contents, or title it will return the object without generated IDs
	// if the post is added the post and any tags will have ids
	@PostMapping("/createPost")
	public ResponseEntity<Object> createPost(@RequestBody Post p) {
		Post returnedPost = postService.addPost(p);
        return new ResponseEntity<>(returnedPost, HttpStatus.OK);
	}
	
	
	@GetMapping("/hello")
    public ResponseEntity<String> hello(@RequestParam(value = "name", defaultValue = "World") String name) {
      return new ResponseEntity<>(String.format("Hello %s!", name), HttpStatus.OK);
    }

}
